# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16wq3CZx1OiZFbAm3xyvZVs2jFTsiqAq8
"""

import random

def Sajeel_Nadeem():
    play_again = "yes"

    for _ in range(100):  # Just a large loop so game can restart
        if play_again.lower() != "yes":
            break

        secret = random.randint(1, 50)
        attempts = 0
        print("\nThink of a number between 1 and 50:\n")

        for _ in range(100):  # Loop for guessing
            guess = int(input("Enter your guess: "))
            attempts += 1

            if guess > secret:
                print("Too high!")    # This will indicate that the number is higher
            elif guess < secret:
                print("Too low!")     # This will indicate that the number is lower
            else:
                print(f"Correct! You guessed it in {attempts} attempts.")
                break

        play_again = input("\nDo you want to play again? (yes/no): ")

# Call the function
Sajeel_Nadeem()